This is makeindex, version 2.15 [MiKTeX 2.9.6800 64-bit] (kpathsea + Thai support).
Scanning style file ./DoW.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file DoW.acn....done (46 entries accepted, 0 rejected).
Sorting entries....done (284 comparisons).
Generating output file DoW.acr....done (36 lines written, 0 warnings).
Output written in DoW.acr.
Transcript written in DoW.alg.
